name: job_match_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0
environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  animated_splash_screen: ^1.3.0
  appinio_swiper: ^2.1.1
  draggable_fab: ^0.1.4
  file_picker: ^8.0.5
  firebase_analytics: ^11.1.0
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.1
  firebase_storage: ^12.0.1
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.1.0
  flutter_dotenv: ^5.1.0
  flutter_gemini: ^2.0.4
  flutter_local_notifications: ^17.1.2
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.2+1
  flutter_riverpod: ^2.5.1
  flutter_spinkit: ^5.2.1
  font_awesome_flutter: ^10.7.0
  go_router: ^14.1.4
  google_generative_ai: ^0.4.3
  google_nav_bar: ^5.0.6
  google_sign_in: ^6.2.1
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  intl: ^0.18.1
  ionicons: ^0.2.2
  lottie: ^3.1.2
  percent_indicator: ^4.2.3
  provider: ^6.1.2
  rive: ^0.13.8
  video_player: ^2.8.6

dev_dependencies:
  cloud_firestore: ^5.0.1
  dio: ^5.4.3+1
  firebase_database: ^11.0.1
  firebase_messaging: ^15.0.1
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  linkedin_login: ^3.0.5
  riverpod: ^2.5.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/video/
    - assets/images/
    - assets/Rive/
flutter_intl:
  enabled: true
  class_name: AppLocalizations
