name: job_match_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  animate_do: ^3.3.4
  animated_splash_screen: ^1.3.0
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  font_awesome_flutter: ^10.7.0
  go_router: ^14.1.4
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  lottie: ^3.1.2
  percent_indicator: ^4.2.3
  video_player: ^2.8.6

dev_dependencies:
  cloud_firestore: ^5.0.1
  dio: ^5.4.3+1
  firebase_database: ^11.0.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  linkedin_login: ^3.0.5
  riverpod: ^2.5.1

flutter:
  uses-material-design: true
  assets:
    - assets/video/
    - assets/images/
