// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfppGzZbByKl-q4xb_vLfcPGPWdMNtFX4',
    appId: '1:875581240489:web:8d4b4a1899c212b81ce5b8',
    messagingSenderId: '875581240489',
    projectId: 'jobmatchdb',
    authDomain: 'jobmatchdb.firebaseapp.com',
    databaseURL: 'https://jobmatchdb-default-rtdb.firebaseio.com',
    storageBucket: 'jobmatchdb.appspot.com',
    measurementId: 'G-JRL891XYNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBES7yl9EZ5UIQ2Ubz_u0YKJuJ_ZljKgaw',
    appId: '1:875581240489:android:81ee2600192a082f1ce5b8',
    messagingSenderId: '875581240489',
    projectId: 'jobmatchdb',
    databaseURL: 'https://jobmatchdb-default-rtdb.firebaseio.com',
    storageBucket: 'jobmatchdb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4_pjTwO7PyiYi8XKiRCg-rG0Cxwdts4Q',
    appId: '1:875581240489:ios:24866507826e8dba1ce5b8',
    messagingSenderId: '875581240489',
    projectId: 'jobmatchdb',
    databaseURL: 'https://jobmatchdb-default-rtdb.firebaseio.com',
    storageBucket: 'jobmatchdb.appspot.com',
    androidClientId: '875581240489-76riakin6f7or7222btsu8u8eee5t2od.apps.googleusercontent.com',
    iosClientId: '875581240489-rdi8imefbv8lm5n9bvhsiaetlif1cnms.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobMatchApp',
  );
}
